name: spm_dart
description: A simple passphrase manager.
version: 1.0.1
repository: https://github.com/pearsche/spm_dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
